---
- name: "include variables for dnf installation of powerline"
  include_vars: dnf.yml

- name: "ensure packages for powerline are installed"
  dnf:
    name: "{{ item }}"
  with_items:
    - powerline
    - powerline-docs
  become: yes

- name: Check if tmux is installed
  command: which tmux
  become: yes
  register: check_tmux

- name: Install package powerline-tmux if tmux is installed
  dnf: name="tmux-powerline" state=present
  become: yes
  when: check_tmux.rc == 0

- name: Check if vim is installed
  command: which vim
  become: yes
  register: check_vim

- name: Install package vim-powerline if vim is installed
  dnf: name="vim-powerline" state=present
  become: yes
  when: check_vim.rc == 0
